### ISSUE TITLE
Requirement subparts CSS formatting

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-csa#12]
The attached is a sample of HTML with recommendations in it, in the CSAND Metanorma flavour. Recommendations are not heavily styled to date, although in OGC recommendations have been styled as having a pale green background. 

The requirement from @ronaldtse is to introduce some CSS styling to these recommendations. I do not know whether this will be permanently incorporated into CSAND or other Metanorma flavours, and I also do not have particular opinions about how this would work.

As you will see from the attached:

Recommendations are signalled by class .recommend; there is also class .permission and .requirement.

Recommendations can be nested.

Recommendations have components, which are presented in HTML as divs, with the classes .requirement-inherit (the recommendation that this recommendation inherits from), .requirement-description, .requirement-specification, .requirement-measurement-target, .requirement-verification, .requirement-import. 

These components can mix normal prose and source code (in `<pre>`).

@ronaldtse will have more opinions than me as to how this should be rendered.

[a.html.zip](https://github.com/metanorma/csa-caiq/files/3126538/a.html.zip)

**Comment by opoudjis** [comment]
@ronaldtse This has never been actioned. Close?

**Comment by ronaldtse** [comment]
Closing.
