### ISSUE TITLE
Rename metanorma-csand to metanorma-csa

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/metanorma-csa#20]
Per https://github.com/metanorma/metanorma-cli/pull/123#issuecomment-569813831 we need to rename all instances of `csand` to `csa`

**Comment by CAMOBAP795** [comment]
@ronaldtse BTW do we have plans to rename this gem to `metanorma-csa` ?

**Comment by ronaldtse** [comment]
@CAMOBAP795 yes we should rename it. Let me rename the repo now.

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you help rename the gemspec and the internal code? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse sure

**Comment by CAMOBAP795** [comment]
Done
