### ISSUE TITLE
Failure to install google/source_code_pro in GHA

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-csa#202]
https://github.com/metanorma/metanorma-csa/actions/runs/8595520893/job/23550460133

**Comment by ronaldtse** [comment]
@opoudjis all Google Fonts are broken in Fontist right now because Google changed their access methods. 
* https://github.com/fontist/formulas/pull/187

**Comment by opoudjis** [comment]
Ah. Got it, thank you, I'll stand by...

**Comment by opoudjis** [comment]
I understand the fix applied is temporary, but no reason to keep this parent issue open...
