### ISSUE TITLE
Add authorship modeling of CSA documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-csa#31]
Add authorship modeling of CSA documents.

They currently have:
* Lead Authors
* Contributors
* Staff ("CSA Global Staff")
* Reviewers

_Originally posted by @opoudjis in https://github.com/metanorma/mn-samples-csa/issues/1#issuecomment-604900867_

**Comment by opoudjis** [comment]
The four requested attributes are roles. Lead author is the default.
