### ISSUE TITLE
Render personal authors if present

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-csa#45]
Follows from https://github.com/metanorma/metanorma-csa/issues/31; personal authors to be rendered with the same XML as in metanorma-cc, except:

* The type of contributor is `//bibdata/contributor/role/@type` if it is not "author"
* The type of contributor is //bibdata/contributor/role/description if `//bibdata/contributor/role/@type` is "author"
* The author type needs to be capitalised
* The sequence of author types is: full-author (omitted), Contributor, Staff, Reviewer

**Comment by opoudjis** [comment]
Current rendering:

[authors.zip](https://github.com/metanorma/metanorma-csa/files/5174755/authors.zip)

**Comment by Intelligent2013** [comment]
Done.

PDF example:
![изображение](https://user-images.githubusercontent.com/5559926/92272536-660f5a80-eef2-11ea-9a95-719b02a7518a.png)
